name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services:
      browser: 
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven   
