name: Actions Wokflow

#on: [push, pull_request]

on: 
  pull_request:
    types: [closed]

jobs:
  runs-github-actions:
    runs-on: ubuntu-latest

    steps:
      - name: List files
        run: |
          pwd
          ls -a 
          echo "Hello World"

