name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: alpine:latest
    steps:
      - name: Log node version
        run: |
          cat /etc/os-release
