name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services:
      browser: 
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
    steps:
      - name: Log node version
        run: |
          cat /etc/os-release
