name: ZAP Baseline scan
on:[push]

jobs:
  ZAP-baseline-scan
    runs-on: ubuntu-latest
    name:  BaselineScan Juice Shop
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          target: 'https://ar-juiceshop.herokuapp.com/#/'
