name: ZAP Baseline scan
on: [push]

jobs:
  ZAP-baseline-scan:
    runs-on: ubuntu-latest
    name: ZAP Baseline scan
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://ar-juiceshop.herokuapp.com/#/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'